security:
    # enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Shared\Entity\SonataUserUser:
            algorithm: auto

    providers:
        sonata_user_bundle:
            id: sonata.user.security.user_provider
        # used to reload user from session & other features (e.g. switch_user)
        # shared_user_provider:
        #     entity:
        #         class: Shared\Entity\SonataUserUser
        #         property: username
    
    role_hierarchy:
        ROLE_ADMIN:             [ROLE_USER, ROLE_ADMIN_ORDER_ALL, ROLE_FA, ROLE_ADMIN_COSTUMER_ALL ]
        ROLE_SUPER_ADMIN:       [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon

        # I cant get log-in when testing to work, so disable access_control for now
        access_control:
            - { path: ^/.*, role: PUBLIC_ACCESS }

        # providers:
        #     users_in_memory:
        #         memory:
        #             users:
        #                 admin: { password: password, roles: ROLE_ADMIN }
        #                 kantine: { password: password, roles: ROLE_USER }