security:
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Required for All-inkl CRON, it only tries authenticating with uses http_basic
        cron:
            lazy: true
            pattern: ^/cron/(.*)
            provider: sonata_user_bundle
            context: user
            http_basic:
                realm: Secured Area
            
        admin:
            # name: admin
            lazy: true
            pattern: ^/admin(.*)
            provider: sonata_user_bundle
            context: user
            form_login:
                login_path: sonata_user_admin_security_login
                check_path: sonata_user_admin_security_check
                default_target_path: sonata_admin_dashboard
            logout:
                path: sonata_user_admin_security_logout
                target: sonata_user_admin_security_login
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 2629746
                path: ^/admin


        main:
            # name: main
            provider: sonata_user_bundle
            context:             user
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_kantine
                enable_csrf: true
            
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 2629746
                path: /
                secure: true
            # access_token:
            #     token_handler: App\Security\AccessTokenHandler

    role_hierarchy:
        ROLE_USER_KANTINE:      [ROLE_ADMIN_ORDER_ALL]
        ROLE_ADMIN:             [ROLE_USER, ROLE_FA, ROLE_USER_KANTINE, ROLE_CRON, ROLE_ADMIN_COSTUMER_ALL ]



# when@prod: &normalAccess
#     security:
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # Admin login page needs to be accessed without credential
        - { path: ^/login$, role: PUBLIC_ACCESS }
        - { path: ^/logout$, role: PUBLIC_ACCESS }
        - { path: ^/admin/login$, role: PUBLIC_ACCESS }
        - { path: ^/admin/logout$, role: PUBLIC_ACCESS }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/.*, role: ROLE_USER }

# when@dev: *normalAccess

